// Code generated by protoc-gen-entconv. DO NOT EDIT.
package entmap

import (
	entpb "github.com/go-sphere/entc-extensions/testdata/api/entpb"
	ent "github.com/go-sphere/entc-extensions/testdata/internal/pkg/database/ent"
)

func ToProtoGroup(e *ent.Group) (*entpb.Group, error) {
	if e == nil {
		return nil, nil
	}
	v := &entpb.Group{}
	active := e.Active
	v.Active = active
	id := e.ID
	v.Id = id
	labels := e.Labels
	v.Labels = labels
	name := e.Name
	v.Name = name
	return v, nil
}

// ToEntGroup converts a pb type to the ent type
func ToEntGroup(v *entpb.Group) (*ent.Group, error) {
	if v == nil {
		return nil, nil
	}
	e := &ent.Group{}
	e.Active = v.Active
	e.ID = int64(v.Id)
	e.Labels = v.Labels
	e.Name = v.Name
	return e, nil
}
