// Code generated by protoc-gen-entconv. DO NOT EDIT.
package entmap

import (
	entpb "github.com/go-sphere/entc-extensions/testdata/api/entpb"
	ent "github.com/go-sphere/entc-extensions/testdata/internal/pkg/database/ent"
	post "github.com/go-sphere/entc-extensions/testdata/internal/pkg/database/ent/post"
)

var (
	// toProtoPost_StatusMap maps Ent enum values to Protobuf enum values
	toProtoPost_StatusMap = map[post.Status]entpb.Post_Status{
		post.StatusPending:    entpb.Post_STATUS_PENDING,
		post.StatusInProgress: entpb.Post_STATUS_IN_PROGRESS,
		post.StatusDone:       entpb.Post_STATUS_DONE,
	}

	// toEntPost_StatusMap maps Protobuf enum values to Ent enum values
	toEntPost_StatusMap = map[entpb.Post_Status]post.Status{
		entpb.Post_STATUS_PENDING:     post.StatusPending,
		entpb.Post_STATUS_IN_PROGRESS: post.StatusInProgress,
		entpb.Post_STATUS_DONE:        post.StatusDone,
	}
)

func ToProtoPost_Status(e post.Status) entpb.Post_Status {
	if v, ok := toProtoPost_StatusMap[e]; ok {
		return v
	}
	return entpb.Post_Status(0)
}

func ToEntPost_Status(e entpb.Post_Status) post.Status {
	if v, ok := toEntPost_StatusMap[e]; ok {
		return v
	}
	return ""
}

func ToProtoPost(e *ent.Post) (*entpb.Post, error) {
	if e == nil {
		return nil, nil
	}
	v := &entpb.Post{}
	content := e.Content
	v.Content = content
	id := int64(e.ID)
	v.Id = id
	likes := e.Likes
	v.Likes = likes
	published := e.Published
	v.Published = published

	status := ToProtoPost_Status(e.Status)
	v.Status = status
	title := e.Title
	v.Title = title
	view_count := int64(e.ViewCount)
	v.ViewCount = view_count
	return v, nil
}

// ToEntPost converts a pb type to the ent type
func ToEntPost(v *entpb.Post) (*ent.Post, error) {
	if v == nil {
		return nil, nil
	}
	e := &ent.Post{}
	e.Content = v.Content
	e.ID = int(v.Id)
	e.Likes = int64(v.Likes)
	e.Published = v.Published
	e.Status = ToEntPost_Status(v.Status)
	e.Title = v.Title
	e.ViewCount = int(v.ViewCount)
	return e, nil
}
