// Code generated by protoc-gen-entconv. DO NOT EDIT.
package entmap

import (
	"time"

	entpb "github.com/go-sphere/entc-extensions/testdata/api/entpb"
	ent "github.com/go-sphere/entc-extensions/testdata/internal/pkg/database/ent"
)

func ToProtoUser(e *ent.User) (*entpb.User, error) {
	if e == nil {
		return nil, nil
	}
	v := &entpb.User{}
	active := e.Active
	v.Active = active
	age := int64(e.Age)
	v.Age = age
	avatar := e.Avatar
	v.Avatar = avatar
	balance := e.Balance
	v.Balance = balance
	birthday := e.Birthday.Unix()
	v.Birthday = birthday
	email := e.Email
	v.Email = email
	id := e.ID
	v.Id = id
	name := e.Name
	v.Name = name
	points := e.Points
	v.Points = points
	quota := e.Quota
	v.Quota = quota
	rank := int32(e.Rank)
	v.Rank = rank
	role := uint32(e.Role)
	v.Role = role
	score := e.Score
	v.Score = score
	status := e.Status
	v.Status = status
	tags := e.Tags
	v.Tags = tags
	return v, nil
}

// ToEntUser converts a pb type to the ent type
func ToEntUser(v *entpb.User) (*ent.User, error) {
	if v == nil {
		return nil, nil
	}
	e := &ent.User{}
	e.Active = v.Active
	e.Age = int(v.Age)
	e.Avatar = v.Avatar
	e.Balance = int64(v.Balance)
	e.Birthday = time.Unix(v.Birthday, 0)
	e.Email = v.Email
	e.ID = int64(v.Id)
	e.Name = v.Name
	e.Points = v.Points
	e.Quota = uint64(v.Quota)
	e.Rank = int8(v.Rank)
	e.Role = uint(v.Role)
	e.Score = float64(v.Score)
	e.Status = v.Status
	e.Tags = v.Tags
	return e, nil
}
