// Code generated by autoproto. DO NOT EDIT.
package mapper

import (
	"fmt"

	"github.com/go-sphere/entc-extensions/example/autoproto/api/entpb"
	"github.com/go-sphere/entc-extensions/example/autoproto/ent"
)

func ToProtoEdgeItem(source *ent.EdgeItem) (*entpb.EdgeItem, error) {
	if source == nil {
		return nil, fmt.Errorf("entproto: nil EdgeItem entity")
	}
	target := &entpb.EdgeItem{}
	target.Id = source.ID
	target.IntValue = int64(source.IntValue)
	target.Int8Value = int32(source.Int8Value)
	target.Int16Value = int32(source.Int16Value)
	target.Int32Value = source.Int32Value
	target.Int64Value = source.Int64Value
	target.UintValue = uint32(source.UintValue)
	target.Uint8Value = uint32(source.Uint8Value)
	target.Uint16Value = uint32(source.Uint16Value)
	target.Uint32Value = source.Uint32Value
	target.Uint64Value = source.Uint64Value
	target.Float32Value = source.Float32Value
	target.FloatValue = source.FloatValue
	target.BoolValue = source.BoolValue
	target.StringValue = source.StringValue
	target.StringsValue = source.StringsValue
	target.BytesValue = source.BytesValue
	target.EnumValue = string(source.EnumValue)
	target.TextValue = source.TextValue
	return target, nil
}

func ToProtoEdgeItemList(sources []*ent.EdgeItem) ([]*entpb.EdgeItem, error) {
	if len(sources) == 0 {
		return nil, nil
	}
	out := make([]*entpb.EdgeItem, 0, len(sources))
	for _, item := range sources {
		if item == nil {
			continue
		}
		res, err := ToProtoEdgeItem(item)
		if err != nil {
			return nil, fmt.Errorf("entproto: convert EdgeItem list: %w", err)
		}
		out = append(out, res)
	}
	return out, nil
}
