// Code generated by protoc-gen-entconv. DO NOT EDIT.
package entpb

import (
	runtime "entgo.io/contrib/entproto/runtime"
	ent "github.com/go-sphere/protocgenentconv/testdata/internal/pkg/database/ent"
	post "github.com/go-sphere/protocgenentconv/testdata/internal/pkg/database/ent/post"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

var (
	// toProtoPost_StatusMap maps Ent enum values to Protobuf enum values
	toProtoPost_StatusMap = map[post.Status]Post_Status{
		post.StatusPending:    Post_STATUS_PENDING,
		post.StatusInProgress: Post_STATUS_IN_PROGRESS,
		post.StatusDone:       Post_STATUS_DONE,
	}

	// toEntPost_StatusMap maps Protobuf enum values to Ent enum values
	toEntPost_StatusMap = map[Post_Status]post.Status{
		Post_STATUS_PENDING:     post.StatusPending,
		Post_STATUS_IN_PROGRESS: post.StatusInProgress,
		Post_STATUS_DONE:        post.StatusDone,
	}
)

func ToProtoPost_Status(e post.Status) Post_Status {
	if v, ok := toProtoPost_StatusMap[e]; ok {
		return v
	}
	return Post_Status(0)
}

func ToEntPost_Status(e Post_Status) post.Status {
	if v, ok := toEntPost_StatusMap[e]; ok {
		return v
	}
	return ""
}

func ToProtoPost(e *ent.Post) (*Post, error) {
	if e == nil {
		return nil, nil
	}
	v := &Post{}
	content := e.Content
	v.Content = content
	id := int64(e.ID)
	v.Id = id
	likes := e.Likes
	v.Likes = likes
	published := e.Published
	v.Published = published
	status := ToProtoPost_Status(e.Status)
	v.Status = status
	title := e.Title
	v.Title = title
	view_count := int64(e.ViewCount)
	v.ViewCount = view_count
	return v, nil
}

// ToEntPost converts a pb type to the ent type
func ToEntPost(v *Post) (*ent.Post, error) {
	if v == nil {
		return nil, nil
	}
	e := &ent.Post{}
	e.Content = v.Content
	e.ID = int(v.Id)
	e.Likes = int64(v.Likes)
	e.Published = v.Published
	e.Status = ToEntPost_Status(v.Status)
	e.Title = v.Title
	e.ViewCount = int(v.ViewCount)
	return e, nil
}

func ToProtoUser(e *ent.User) (*User, error) {
	if e == nil {
		return nil, nil
	}
	v := &User{}
	active := e.Active
	v.Active = active
	age := int64(e.Age)
	v.Age = age
	avatar := e.Avatar
	v.Avatar = avatar
	balance := e.Balance
	v.Balance = balance
	birthday := timestamppb.New(e.Birthday)
	v.Birthday = birthday
	email := e.Email
	v.Email = email
	id := e.ID
	v.Id = id
	name := e.Name
	v.Name = name
	role := uint32(e.Role)
	v.Role = role
	score := e.Score
	v.Score = score
	status := e.Status
	v.Status = status
	return v, nil
}

// ToEntUser converts a pb type to the ent type
func ToEntUser(v *User) (*ent.User, error) {
	if v == nil {
		return nil, nil
	}
	e := &ent.User{}
	e.Active = v.Active
	e.Age = int(v.Age)
	e.Avatar = v.Avatar
	e.Balance = int64(v.Balance)
	e.Birthday = runtime.ExtractTime(v.Birthday)
	e.Email = v.Email
	e.ID = int64(v.Id)
	e.Name = v.Name
	e.Role = uint(v.Role)
	e.Score = float64(v.Score)
	e.Status = v.Status
	return e, nil
}
