// Code generated by Sphere. DO NOT EDIT.
package entbind

import (
	"github.com/go-sphere/entc-extensions/testdata/api/entpb"
	"github.com/go-sphere/entc-extensions/testdata/internal/pkg/database/ent"
	"github.com/go-sphere/entc-extensions/testdata/internal/pkg/database/ent/group"
)

func CreateGroup(source *ent.GroupCreate, target *entpb.Group, options ...Option) *ent.GroupCreate {
	option := NewBindOptions(options...)
	if option.CanSetField(group.FieldName) {
		if option.CanSetZero(group.FieldName) || target.Name != "" {
			source.SetName(target.Name)
		}
	}
	if option.CanSetField(group.FieldActive) {
		if option.CanSetZero(group.FieldActive) || target.Active {
			source.SetActive(target.Active)
		}
	}
	if option.CanSetField(group.FieldLabels) {
		if option.CanSetZero(group.FieldLabels) || target.Labels != nil {
			source.SetLabels(target.Labels)
		}
	}
	return source
}

func UpdateOneGroup(source *ent.GroupUpdateOne, target *entpb.Group, options ...Option) *ent.GroupUpdateOne {
	option := NewBindOptions(options...)
	if option.CanSetField(group.FieldName) {
		if option.CanSetZero(group.FieldName) || target.Name != "" {
			source.SetName(target.Name)
		}
	}
	if option.CanSetField(group.FieldActive) {
		if option.CanSetZero(group.FieldActive) || target.Active {
			source.SetActive(target.Active)
		}
	}
	if option.CanSetField(group.FieldLabels) {
		if option.CanSetZero(group.FieldLabels) || target.Labels != nil {
			source.SetLabels(target.Labels)
		}
	}
	return source
}
