// Code generated by Sphere. DO NOT EDIT.
package entbind

import (
	"github.com/go-sphere/entc-extensions/testdata/api/entpb"
	"github.com/go-sphere/entc-extensions/testdata/internal/pkg/database/ent"
	"github.com/go-sphere/entc-extensions/testdata/internal/pkg/database/ent/post"
	"github.com/go-sphere/entc-extensions/testdata/internal/pkg/render/entmap"
)

func CreatePost(source *ent.PostCreate, target *entpb.Post, options ...Option) *ent.PostCreate {
	option := NewBindOptions(options...)
	if option.CanSetField(post.FieldID) {
		if option.CanSetZero(post.FieldID) || target.Id != 0 {
			source.SetID(int(target.Id))
		}
	}
	if option.CanSetField(post.FieldTitle) {
		if option.CanSetZero(post.FieldTitle) || target.Title != "" {
			source.SetTitle(target.Title)
		}
	}
	if option.CanSetField(post.FieldContent) {
		if option.CanSetZero(post.FieldContent) || target.Content != "" {
			source.SetContent(target.Content)
		}
	}
	if option.CanSetField(post.FieldViewCount) {
		if option.CanSetZero(post.FieldViewCount) || target.ViewCount != 0 {
			source.SetViewCount(int(target.ViewCount))
		}
	}
	if option.CanSetField(post.FieldPublished) {
		if option.CanSetZero(post.FieldPublished) || target.Published {
			source.SetPublished(target.Published)
		}
	}
	if option.CanSetField(post.FieldStatus) {
		source.SetStatus(entmap.ToEntPost_Status(target.Status))
	}
	if option.CanSetField(post.FieldLikes) {
		if option.CanSetZero(post.FieldLikes) || target.Likes != 0 {
			source.SetLikes(target.Likes)
		}
	}
	if option.CanSetField(post.FieldShares) {
		if option.CanSetZero(post.FieldShares) || target.Shares != 0 {
			source.SetShares(target.Shares)
		}
	}
	return source
}

func UpdateOnePost(source *ent.PostUpdateOne, target *entpb.Post, options ...Option) *ent.PostUpdateOne {
	option := NewBindOptions(options...)
	if option.CanSetField(post.FieldTitle) {
		if option.CanSetZero(post.FieldTitle) || target.Title != "" {
			source.SetTitle(target.Title)
		}
	}
	if option.CanSetField(post.FieldContent) {
		if option.CanSetZero(post.FieldContent) || target.Content != "" {
			source.SetContent(target.Content)
		}
	}
	if option.CanSetField(post.FieldViewCount) {
		if option.CanSetZero(post.FieldViewCount) || target.ViewCount != 0 {
			source.SetViewCount(int(target.ViewCount))
		}
	}
	if option.CanSetField(post.FieldPublished) {
		if option.CanSetZero(post.FieldPublished) || target.Published {
			source.SetPublished(target.Published)
		}
	}
	if option.CanSetField(post.FieldStatus) {
		if option.CanSetZero(post.FieldStatus) || target.Status != 0 {
			source.SetStatus(entmap.ToEntPost_Status(target.Status))
		}
	}
	if option.CanSetField(post.FieldLikes) {
		if option.CanSetZero(post.FieldLikes) || target.Likes != 0 {
			source.SetLikes(target.Likes)
		}
	}
	if option.CanSetField(post.FieldShares) {
		if option.CanSetZero(post.FieldShares) || target.Shares != 0 {
			source.SetShares(target.Shares)
		}
	}
	return source
}
