// Code generated by Sphere. DO NOT EDIT.
package entbind

import (
	"github.com/go-sphere/entc-extensions/testdata/api/entpb"
	"github.com/go-sphere/entc-extensions/testdata/internal/pkg/conv"
	"github.com/go-sphere/entc-extensions/testdata/internal/pkg/database/ent"
	"github.com/go-sphere/entc-extensions/testdata/internal/pkg/database/ent/user"
)

func CreateUser(source *ent.UserCreate, target *entpb.User, options ...Option) *ent.UserCreate {
	option := NewBindOptions(options...)
	if option.CanSetField(user.FieldName) {
		if option.CanSetZero(user.FieldName) || target.Name != "" {
			source.SetName(target.Name)
		}
	}
	if option.CanSetField(user.FieldAge) {
		if option.CanSetZero(user.FieldAge) || target.Age != 0 {
			source.SetAge(int(target.Age))
		}
	}
	if option.CanSetField(user.FieldActive) {
		if option.CanSetZero(user.FieldActive) || target.Active {
			source.SetActive(target.Active)
		}
	}
	if option.CanSetField(user.FieldScore) {
		if option.CanSetZero(user.FieldScore) || target.Score != 0.0 {
			source.SetScore(target.Score)
		}
	}
	if option.CanSetField(user.FieldBirthday) {
		source.SetBirthday(conv.ToEntUserBirthday(target.Birthday))
	}
	if option.CanSetField(user.FieldAvatar) {
		if option.CanSetZero(user.FieldAvatar) || target.Avatar != nil {
			source.SetAvatar(target.Avatar)
		}
	}
	if option.CanSetField(user.FieldStatus) {
		if option.CanSetZero(user.FieldStatus) || target.Status != "" {
			source.SetStatus(target.Status)
		}
	}
	if option.CanSetField(user.FieldEmail) {
		if option.CanSetZero(user.FieldEmail) || target.Email != "" {
			source.SetEmail(target.Email)
		}
	}
	if option.CanSetField(user.FieldBalance) {
		if option.CanSetZero(user.FieldBalance) || target.Balance != 0 {
			source.SetBalance(target.Balance)
		}
	}
	if option.CanSetField(user.FieldRole) {
		if option.CanSetZero(user.FieldRole) || target.Role != 0 {
			source.SetRole(uint(target.Role))
		}
	}
	if option.CanSetField(user.FieldRank) {
		if option.CanSetZero(user.FieldRank) || target.Rank != 0 {
			source.SetRank(int8(target.Rank))
		}
	}
	if option.CanSetField(user.FieldQuota) {
		if option.CanSetZero(user.FieldQuota) || target.Quota != 0 {
			source.SetQuota(target.Quota)
		}
	}
	if option.CanSetField(user.FieldTags) {
		if option.CanSetZero(user.FieldTags) || target.Tags != nil {
			source.SetTags(target.Tags)
		}
	}
	if option.CanSetField(user.FieldPoints) {
		if option.CanSetZero(user.FieldPoints) || target.Points != nil {
			source.SetPoints(target.Points)
		}
	}
	return source
}

func UpdateOneUser(source *ent.UserUpdateOne, target *entpb.User, options ...Option) *ent.UserUpdateOne {
	option := NewBindOptions(options...)
	if option.CanSetField(user.FieldName) {
		if option.CanSetZero(user.FieldName) || target.Name != "" {
			source.SetName(target.Name)
		}
	}
	if option.CanSetField(user.FieldAge) {
		if option.CanSetZero(user.FieldAge) || target.Age != 0 {
			source.SetAge(int(target.Age))
		}
	}
	if option.CanSetField(user.FieldActive) {
		if option.CanSetZero(user.FieldActive) || target.Active {
			source.SetActive(target.Active)
		}
	}
	if option.CanSetField(user.FieldScore) {
		if option.CanSetZero(user.FieldScore) || target.Score != 0.0 {
			source.SetScore(target.Score)
		}
	}
	if option.CanSetField(user.FieldBirthday) {
		if option.CanSetZero(user.FieldBirthday) || target.Birthday != 0 {
			source.SetBirthday(conv.ToEntUserBirthday(target.Birthday))
		}
	}
	if option.CanSetField(user.FieldAvatar) {
		if option.CanSetZero(user.FieldAvatar) || target.Avatar != nil {
			source.SetAvatar(target.Avatar)
		}
	}
	if option.CanSetField(user.FieldStatus) {
		if option.CanSetZero(user.FieldStatus) || target.Status != "" {
			source.SetStatus(target.Status)
		}
	}
	if option.CanSetField(user.FieldEmail) {
		if option.CanSetZero(user.FieldEmail) || target.Email != "" {
			source.SetEmail(target.Email)
		}
	}
	if option.CanSetField(user.FieldBalance) {
		if option.CanSetZero(user.FieldBalance) || target.Balance != 0 {
			source.SetBalance(target.Balance)
		}
	}
	if option.CanSetField(user.FieldRole) {
		if option.CanSetZero(user.FieldRole) || target.Role != 0 {
			source.SetRole(uint(target.Role))
		}
	}
	if option.CanSetField(user.FieldRank) {
		if option.CanSetZero(user.FieldRank) || target.Rank != 0 {
			source.SetRank(int8(target.Rank))
		}
	}
	if option.CanSetField(user.FieldQuota) {
		if option.CanSetZero(user.FieldQuota) || target.Quota != 0 {
			source.SetQuota(target.Quota)
		}
	}
	if option.CanSetField(user.FieldTags) {
		if option.CanSetZero(user.FieldTags) || target.Tags != nil {
			source.SetTags(target.Tags)
		}
	}
	if option.CanSetField(user.FieldPoints) {
		if option.CanSetZero(user.FieldPoints) || target.Points != nil {
			source.SetPoints(target.Points)
		}
	}
	return source
}
