package entconv

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"entgo.io/ent/entc/gen"
	"github.com/go-sphere/entc-extensions/entconv/internal/pkgutil"
)

// IDTypeMismatchError reports a divergence between the ID type assumed by
// entconv (driven by the IDType option via the loaded ent graph) and the ID
// type declared by the real generated ent struct on disk.
type IDTypeMismatchError struct {
	Entity       string
	ExpectedType string // ID type assumed by entconv (from the ent graph).
	ActualType   string // ID type of the real generated ent struct.
	Suggestion   string
}

func (e *IDTypeMismatchError) Error() string {
	if e.Suggestion == "" {
		return fmt.Sprintf(
			"entconv: ent type %s has ID of Go type %s, but the converter would be generated for ID type %s",
			e.Entity, e.ActualType, e.ExpectedType,
		)
	}
	return fmt.Sprintf(
		"entconv: ent type %s has ID of Go type %s, but the converter would be generated for ID type %s: %s",
		e.Entity, e.ActualType, e.ExpectedType, e.Suggestion,
	)
}

// verifyIDTypesAgainstSource checks, for every schema node, that the ID Go type
// entconv derived from the ent graph (via the IDType option) matches the ID
// field type of the real generated ent struct. It is a no-op when the real ent
// source cannot be located (e.g. it has not been generated yet), in which case
// the IDType option remains the single source of truth.
//
// The ent package directory is resolved from entPackage (the configured import
// path, mapped onto disk) first, falling back to a sibling "ent" directory
// (covers the entc default layout <project>/ent/schema -> <project>/ent and the
// <project>/<pkg>/database/{schema,ent} layout).
func verifyIDTypesAgainstSource(g *gen.Graph, schemaDir, entPackage string) error {
	entDir := resolveEntDir(schemaDir, entPackage)
	if entDir == "" {
		return nil
	}
	for _, node := range g.Nodes {
		actual, ok := structIDType(entDir, node.Name)
		if !ok {
			// Generated source not available yet; trust the IDType option.
			continue
		}
		expected := node.ID.Type.String()
		if idTypeNamesEqual(expected, actual) {
			continue
		}
		return &IDTypeMismatchError{
			Entity:       node.Name,
			ExpectedType: expected,
			ActualType:   actual,
			Suggestion:   fmt.Sprintf("set the IDType option to %q to match the ID type generated by entc", actual),
		}
	}
	return nil
}

// resolveEntDir returns the on-disk directory of the generated ent package.
// It prefers the configured ent import path (which handles the entc default
// <project>/ent/schema layout where a naive sibling lookup would look for
// <project>/ent/ent), then falls back to a sibling "ent" directory.
func resolveEntDir(schemaDir, entPackage string) string {
	if entPackage != "" {
		if dir, err := pkgutil.DiskDirForImportPath(schemaDir, entPackage); err == nil {
			if info, err := os.Stat(dir); err == nil && info.IsDir() {
				return dir
			}
		}
	}
	return entDirBesideSchema(schemaDir)
}

// entDirBesideSchema returns the directory of the generated ent package when it
// sits next to the schema directory. Empty when undeterminable.
func entDirBesideSchema(schemaDir string) string {
	abs, err := filepath.Abs(schemaDir)
	if err != nil {
		return ""
	}
	candidate := filepath.Join(filepath.Dir(abs), "ent")
	if info, err := os.Stat(candidate); err == nil && info.IsDir() {
		return candidate
	}
	return ""
}

// structIDType parses the generated ent source files in entDir and returns the
// declared type of typeName's ID field. It scans every .go file rather than
// assuming entc's lower-cased file naming, so custom layouts keep working.
func structIDType(entDir, typeName string) (string, bool) {
	entries, err := os.ReadDir(entDir)
	if err != nil {
		return "", false
	}
	fset := token.NewFileSet()
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".go" {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(entDir, entry.Name()), nil, 0)
		if err != nil {
			continue
		}
		if idType, ok := structIDTypeInFile(f, typeName); ok {
			return idType, true
		}
	}
	return "", false
}

func structIDTypeInFile(f *ast.File, typeName string) (string, bool) {
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != typeName {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, fld := range st.Fields.List {
				for _, name := range fld.Names {
					if name.Name == "ID" {
						return exprString(fld.Type), true
					}
				}
			}
		}
	}
	return "", false
}

func exprString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		if pkg, ok := t.X.(*ast.Ident); ok {
			return pkg.Name + "." + t.Sel.Name
		}
		return t.Sel.Name
	case *ast.StarExpr:
		if inner := exprString(t.X); inner != "" {
			return "*" + inner
		}
	case *ast.ArrayType:
		if inner := exprString(t.Elt); inner != "" {
			return "[]" + inner
		}
	}
	return ""
}

// idTypeNamesEqual compares two Go type spellings for ID fields, tolerating a
// package qualifier difference (e.g. "uuid.UUID" vs "UUID" when the importing
// package differs).
func idTypeNamesEqual(a, b string) bool {
	a = strings.TrimSpace(a)
	b = strings.TrimSpace(b)
	if a == b {
		return true
	}
	strip := func(s string) string {
		if i := strings.LastIndex(s, "."); i >= 0 {
			return s[i+1:]
		}
		return s
	}
	return strip(a) == strip(b)
}
