package entconv

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"entgo.io/ent/entc/gen"
)

// IDTypeMismatchError reports a divergence between the ID type assumed by
// entconv (driven by the IDType option via the loaded ent graph) and the ID
// type declared by the real generated ent struct on disk.
type IDTypeMismatchError struct {
	Entity       string
	ExpectedType string // ID type assumed by entconv (from the ent graph).
	ActualType   string // ID type of the real generated ent struct.
	Suggestion   string
}

func (e *IDTypeMismatchError) Error() string {
	if e.Suggestion == "" {
		return fmt.Sprintf(
			"entconv: ent type %s has ID of Go type %s, but the converter would be generated for ID type %s",
			e.Entity, e.ActualType, e.ExpectedType,
		)
	}
	return fmt.Sprintf(
		"entconv: ent type %s has ID of Go type %s, but the converter would be generated for ID type %s: %s",
		e.Entity, e.ActualType, e.ExpectedType, e.Suggestion,
	)
}

// verifyIDTypesAgainstSource checks, for every schema node, that the ID Go type
// entconv derived from the ent graph (via the IDType option) matches the ID
// field type of the real generated ent struct. It is a no-op when the real ent
// source cannot be located (e.g. it has not been generated yet), in which case
// the IDType option remains the single source of truth.
//
// The entc default layout is <project>/ent/schema -> <project>/ent, so the ent
// package directory is derived as a sibling of the schema directory. When the
// schema directory is not named "schema", a direct sibling named "ent" is still
// attempted as a best effort.
func verifyIDTypesAgainstSource(g *gen.Graph, schemaDir string) error {
	entDir := entDirBesideSchema(schemaDir)
	if entDir == "" {
		return nil
	}
	for _, node := range g.Nodes {
		actual, ok := structIDType(entDir, node.Name)
		if !ok {
			// Generated source not available yet; trust the IDType option.
			continue
		}
		expected := node.ID.Type.String()
		if idTypeNamesEqual(expected, actual) {
			continue
		}
		return &IDTypeMismatchError{
			Entity:       node.Name,
			ExpectedType: expected,
			ActualType:   actual,
			Suggestion:   fmt.Sprintf("set the IDType option to %q to match the ID type generated by entc", actual),
		}
	}
	return nil
}

// entDirBesideSchema returns the directory of the generated ent package when it
// sits next to the schema directory (the entc default layout:
// <project>/ent/schema -> <project>/ent). Empty when undeterminable.
func entDirBesideSchema(schemaDir string) string {
	abs, err := filepath.Abs(schemaDir)
	if err != nil {
		return ""
	}
	candidate := filepath.Join(filepath.Dir(abs), "ent")
	if info, err := os.Stat(candidate); err == nil && info.IsDir() {
		return candidate
	}
	return ""
}

// structIDType parses the generated ent source file for typeName and returns the
// declared type of its ID field.
func structIDType(entDir, typeName string) (string, bool) {
	// entc writes each type to a lower-cased file name (user.go, userprofile.go).
	file := filepath.Join(entDir, strings.ToLower(typeName)+".go")
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, file, nil, 0)
	if err != nil {
		return "", false
	}
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != typeName {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, fld := range st.Fields.List {
				for _, name := range fld.Names {
					if name.Name == "ID" {
						return exprString(fld.Type), true
					}
				}
			}
		}
	}
	return "", false
}

func exprString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		if pkg, ok := t.X.(*ast.Ident); ok {
			return pkg.Name + "." + t.Sel.Name
		}
		return t.Sel.Name
	case *ast.StarExpr:
		if inner := exprString(t.X); inner != "" {
			return "*" + inner
		}
	case *ast.ArrayType:
		if inner := exprString(t.Elt); inner != "" {
			return "[]" + inner
		}
	}
	return ""
}

// idTypeNamesEqual compares two Go type spellings for ID fields, tolerating a
// package qualifier difference (e.g. "uuid.UUID" vs "UUID" when the importing
// package differs).
func idTypeNamesEqual(a, b string) bool {
	a = strings.TrimSpace(a)
	b = strings.TrimSpace(b)
	if a == b {
		return true
	}
	strip := func(s string) string {
		if i := strings.LastIndex(s, "."); i >= 0 {
			return s[i+1:]
		}
		return s
	}
	return strip(a) == strip(b)
}
