package gofile

import (
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"

	"github.com/go-sphere/entc-extensions/autoproto/utils/inspect"
	"golang.org/x/tools/imports"
)

func WriteFile(fileName string, content []byte) error {
	content, err := imports.Process(fileName, content, nil)
	if err != nil {
		return err
	}
	content, err = format.Source(content)
	if err != nil {
		return err
	}
	err = os.WriteFile(fileName, content, 0o644)
	if err != nil {
		return err
	}
	return nil
}

func CreateGoFile(pkgName string, pkgImports [][2]string, body string) string {
	var file strings.Builder
	file.WriteString("// Code generated by Sphere. DO NOT EDIT.\n")
	file.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	file.WriteString("import (\n")
	for _, imp := range inspect.DeduplicateImports(pkgImports) {
		file.WriteString("\t")
		if imp[1] != "" {
			file.WriteString(imp[1] + " ")
		}
		file.WriteString(strconv.Quote(imp[0]))
		file.WriteString("\n")
	}
	file.WriteString(")\n\n")
	file.WriteString(body)
	return file.String()
}
