package bind

import (
	_ "embed"
	"strings"
)

//go:embed options.go
var optionsFile string

// CreateOptionsFile re-emits the shared options source into the caller's
// package. The embedded file is expected to declare `package bind` on its first
// line; only that exact declaration is rewritten.
func CreateOptionsFile(pkg string) string {
	body := optionsFile
	body, _ = strings.CutPrefix(body, "package bind")
	return "// Code generated by Sphere. DO NOT EDIT.\n" +
		"package " + pkg + "\n" + body
}
